# Generated by Django 5.0.6 on 2024-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='music/')),
                ('author', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='music/pic/')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='album/pic/')),
                ('likes', models.IntegerField(default=0)),
                ('songs', models.ManyToManyField(related_name='albums', to='main.music')),
            ],
        ),
    ]
