# Generated by Django 5.0.6 on 2024-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='songs',
            new_name='albums',
        ),
    ]
