# Generated by Django 5.0.6 on 2024-07-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_songs_category_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-id'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-id'], 'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыка'},
        ),
    ]
